language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      jmazzi@gmail.com
    on_success: never
    on_failure: always
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode

jdk:
  - openjdk7
